version: "3"

services:

  db:
    build: ./db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testeCoontrol"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    networks: 
      - default
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5